btcbyme/messages/routes.py
from datetime import datetime

from flask import render_template, Blueprint, abort, redirect, url_for, flash
from flask_login import login_required, current_user
from btcbyme import db, limiter
from btcbyme.messages.forms import NewMessageForm
from btcbyme.models import MessageThread, Message, Post
from btcbyme.utilities import utilities


messages = Blueprint('messages', __name__)


@messages.route('/messages')
@login_required
@limiter.limit('500/day; 100/hour;', override_defaults=True)
def index_messages():
    user_message_threads = list(MessageThread.query.filter(
        (MessageThread.sender_id == current_user.get_id()) |
        (MessageThread.recipient_id == current_user.get_id())
    ).order_by(MessageThread.date_updated.desc()))
    user_message_threads_data = utilities.get_message_thread_view_data(user_message_threads)
    return render_template('messages.html', title='Messages', user_message_threads_data=user_message_threads_data)


@messages.route('/messages/new_thread/<string:post_id>', methods=['GET', 'POST'])
@login_required
def new_message_thread(post_id):
    form = NewMessageForm()
    post = Post.query.get_or_404(post_id)
    if form.validate_on_submit():
        now_utc = datetime.utcnow()
        new_thread_uuid = utilities.create_uuid()
        new_thread = MessageThread(
            id=new_thread_uuid, date_updated=now_utc, sender_id=current_user.get_id(),
            recipient_id=post.user_id, post_id=post.id)
        new_message = Message(
            id=utilities.create_uuid(),
            recipient_id=post.user_id, sender_id=current_user.get_id(), content=form.content.data,
            thread_id=new_thread_uuid, date_sent=now_utc)
        db.session.add(new_thread)
        db.session.add(new_message)
        db.session.commit()
        return redirect(url_for('messages.message_thread', thread_id=new_thread_uuid))
    post_view_data = utilities.get_posts_view_data([post])[0]
    return render_template('new_thread.html', title='New Thread', post_data=post_view_data, form=form)


@messages.route('/messages/<string:thread_id>', methods=['GET', 'POST'])
@login_required
def message_thread(thread_id):
    thread = MessageThread.query.get_or_404(thread_id)
    if not (current_user.get_id() == str(thread.sender_id) or
            current_user.get_id() == str(thread.recipient_id)):
        abort(403)
    form = NewMessageForm()
    if form.validate_on_submit():
        now_utc = datetime.utcnow()
        new_message = Message(
            id=utilities.create_uuid(),
            recipient_id=thread.recipient_id if current_user.get_id() != thread.recipient_id else thread.sender_id,
            sender_id=current_user.get_id(),
            content=form.content.data, thread_id=thread.id, date_sent=now_utc)
        thread.date_updated = now_utc
        db.session.add(new_message)
        db.session.commit()
        return redirect(url_for('messages.message_thread', thread_id=thread.id))
    thread_data = utilities.get_message_thread_view_data([thread])[0]
    thread_messages = Message.query.filter_by(thread_id=thread.id).order_by(Message.date_sent.asc())
    messages_data = utilities.process_messages_data(thread_messages, thread_data)
    return render_template(
        'thread.html', title=f'Thread {thread.id}', messages_data=messages_data, thread_data=thread_data, form=form)


@messages.route('/messages/<string:thread_id>/delete', methods=['POST', 'GET'])
@login_required
def delete_message_thread(thread_id):
    thread = MessageThread.query.get_or_404(thread_id)
    thread_messages = Message.query.filter_by(thread_id=thread.id)
    if not (current_user.get_id() == thread.sender_id or
            current_user.get_id() == thread.recipient_id):
        abort(403)
    db.session.delete(thread)
    for message in thread_messages:
        db.session.delete(message)
    db.session.commit()
    flash(f'Message thread {thread.id} has been deleted!', 'success')
    return redirect(url_for('messages.index_messages'))

btcbyme/posts/routes.py
from datetime import datetime

from flask import render_template, Blueprint, flash, redirect, url_for, abort, session
from flask_login import login_required, current_user
from btcbyme.posts.forms import NewPostForm, NewPostConfirmationForm, SearchPostForm
from btcbyme import db, limiter
from btcbyme.models import Post, Persistent
from btcbyme.utilities import utilities
from btcpay import BTCPayClient


posts = Blueprint('posts', __name__)


@posts.route('/posts')
@login_required
@limiter.limit('500/day; 100/hour;', override_defaults=True)
def index_posts():
    user_posts = Post.query.filter_by(
        user_id=current_user.get_id()).order_by(Post.date_posted.desc())
    user_posts_view_data = utilities.get_posts_view_data(user_posts)
    return render_template(
        'user_posts.html', title='Posts', posts=user_posts_view_data)


@posts.route('/posts/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = NewPostForm()
    if form.validate_on_submit():
        geocoded_post_data = utilities.get_geocoded_post_info(
            ','.join(filter(None, [form.city.data, form.region.data, form.country.data])))
        if geocoded_post_data is None:
            flash(f'Unable to create post.', 'danger')
            return redirect(url_for('posts.index_posts'))
        post = Post(
            id=utilities.create_uuid(),
            markup=form.markup.data, min_tx=form.min_tx.data,
            max_tx=form.max_tx.data, latitude=geocoded_post_data.lat, longitude=geocoded_post_data.lon,
            city=geocoded_post_data.place_name, user_id=current_user.get_id(), currency=form.currency.data)
        encoded_post_data = utilities.encode_post_data(post)
        if encoded_post_data is None:
            flash(f'Unable to create post.', 'danger')
            return redirect(url_for('posts.index_posts'))
        return redirect(url_for('posts.new_post_confirmation', encoded_candidate_post=encoded_post_data))
    return render_template('new_post.html', title='New Post', form=form)


@posts.route('/posts/new/confirm/<string:encoded_candidate_post>', methods=['GET', 'POST'])
@login_required
def new_post_confirmation(encoded_candidate_post):
    candidate_post = utilities.decode_post_data(encoded_candidate_post)
    if candidate_post is None:
        flash(f'Unable to create post.', 'danger')
        return redirect(url_for('posts.index_posts'))
    if candidate_post.user_id != current_user.get_id():
        return abort(403)
    form = NewPostConfirmationForm()
    # Format view data.
    candidate_post.date_posted = datetime.utcnow()
    post_view_data = utilities.get_posts_view_data([candidate_post])[0]
    formatted_post_price = (utilities.SUPPORTED_CURRENCIES_SYMBOLS['USD'] +
                            utilities.format_price(utilities.POST_PRICE_USD))
    # Create invoice.
    persistent_client = Persistent.query.all()
    if len(persistent_client) != 1:
        flash(f'Unable to create post. Failed to retrieve BTCPay client.', 'danger')
        return redirect(url_for('posts.index_posts'))
    client = persistent_client[0].btcpay_server_client
    # If we are experiencing a new candidate post, create a new invoice and update session values.
    if session.get('new_post_id') is None or session.get('new_post_id') != candidate_post.id:
        new_invoice = client.create_invoice({"price": utilities.POST_PRICE_USD, "currency": "USD"})
        session['new_invoice_id'] = new_invoice['id']
        session['new_post_id'] = candidate_post.id
    if form.validate_on_submit():
        # Check post/invoice assumptions.
        new_invoice_id = session.get('new_invoice_id')
        new_post_id = session.get('new_post_id')
        if new_invoice_id is None or candidate_post.id != new_post_id:
            flash(f'Unable to create post. Invalid invoice ID.', 'danger')
            return redirect(url_for('posts.new_post'))
        # Verify required invoice status.
        fetch_invoice = client.get_invoice(new_invoice_id)
        if not (fetch_invoice['status'] in utilities.ACCEPTED_BTCPAY_SERVER_TX_STATUS):
            flash(f'Unable to create post. Transaction was not completed successfully.', 'danger')
            return redirect(url_for('posts.new_post'))
        if len(Post.query.filter_by(user_id=current_user.get_id()).all()) == utilities.MAX_POST_COUNT_PER_USER:
            flash(f'Unable to create post. Maximum post count reached.', 'danger')
            return redirect(url_for('posts.index_posts'))
        db.session.add(candidate_post)
        db.session.commit()
        flash(f'Your post has been created in {candidate_post.city}.', 'success')
        return redirect(url_for('posts.index_posts'))
    return render_template(
        'new_post_confirmation.html', title='Confirm Post', post=post_view_data, form=form,
        invoice_id=session['new_invoice_id'], post_price=formatted_post_price)


@posts.route('/posts/<string:post_id>', methods=['GET'])
def view_post(post_id):
    post = Post.query.get_or_404(post_id)
    post_view_data = utilities.get_posts_view_data([post])[0]
    return render_template(
        'post.html', title=f'Post {post_view_data.id}', post=post_view_data)


@posts.route('/posts/search', methods=['GET', 'POST'])
def search_posts():
    form = SearchPostForm()
    if form.validate_on_submit():
        search_filters = [set(Post.query.filter(Post.currency == form.currency.data).all())]
        # Access location data input, add to search filters if valid.
        location_data = list(filter(None, [form.city.data, form.region.data, form.country.data]))
        geocoded_post_data = None
        if len(location_data):
            geocoded_post_data = utilities.get_geocoded_post_info(','.join(location_data))
            search_bounding_box = utilities.get_lat_lon_bounding_box(
                geocoded_post_data.lat, geocoded_post_data.lon, form.search_distance.data)
            search_filters.append(set(Post.query.filter((Post.latitude >= search_bounding_box.min_lat) &
                                                        (Post.latitude <= search_bounding_box.max_lat) &
                                                        (Post.longitude >= search_bounding_box.min_lon) &
                                                        (Post.longitude <= search_bounding_box.max_lon))))
        # Access other data fields and add to search filters.
        if form.max_markup.data is not None:
            search_filters.append(set(Post.query.filter(Post.markup <= form.max_markup.data).all()))
        desired_tx_amount_data = form.desired_tx_amount.data
        if desired_tx_amount_data is not None:
            search_filters.append(set(
                Post.query.filter((Post.min_tx <= desired_tx_amount_data) &
                                  (Post.max_tx >= desired_tx_amount_data)).all()))
        # Perform an intersection on the search criteria. Limit the results to only the first 50 (for now).
        search_filters_results = list(set.intersection(*search_filters)) if len(search_filters) else []
        if len(search_filters_results) > 50:
            search_filters_results = search_filters_results[:50]
        # Apply sorting criteria.
        sorting_parameter = form.sort_by.data
        if sorting_parameter == utilities.SEARCH_SORTING_OPTIONS[0]:
            utilities.sort_posts(utilities.SearchSortingOptions.MARKUP_LOW_HIGH, search_filters_results)
        elif sorting_parameter == utilities.SEARCH_SORTING_OPTIONS[1]:
            utilities.sort_posts(utilities.SearchSortingOptions.MARKUP_HIGH_LOW, search_filters_results)
        elif sorting_parameter == utilities.SEARCH_SORTING_OPTIONS[2]:
            utilities.sort_posts(utilities.SearchSortingOptions.DATE_NEW_OLD, search_filters_results)
        elif sorting_parameter == utilities.SEARCH_SORTING_OPTIONS[3]:
            if geocoded_post_data is not None:
                utilities.sort_posts(
                    utilities.SearchSortingOptions.DISTANCE_LOW_HIGH, search_filters_results, geocoded_post_data)
            else:
                flash('Sorting by distance is not allowed if no location information ' +
                      '(city, state/region, or country) is provided.', 'danger')
                return render_template(
                    'search_posts.html', title=f'Search Posts', form=form, posts=None,
                    geocoded_post_data=geocoded_post_data)
        currency_symbol = utilities.SUPPORTED_CURRENCIES_SYMBOLS[form.currency.data]
        btc_price_data = utilities.get_btc_price_per_currency()
        original_btc_price_formatted = (currency_symbol +
                                        utilities.format_price(utilities.get_btc_price_from_data(
                                            btc_price_data, currency_symbol)))
        posts_view_data = utilities.get_posts_view_data(search_filters_results, btc_price_data=btc_price_data)
        return render_template(
            'search_posts.html', title=f'Search Posts', form=form, posts=posts_view_data,
            geocoded_post_data=geocoded_post_data, original_btc_price=original_btc_price_formatted)
    return render_template(
        'search_posts.html', title=f'Search Posts', form=form, posts=None, geocoded_post_data=None)


@posts.route('/post/<string:post_id>/delete', methods=['POST', 'GET'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('posts.index_posts'))

btcbyme/users/routes.py
from flask import render_template, Blueprint, flash, redirect, url_for, request
from flask_limiter.util import get_remote_address
from flask_login import login_user, current_user, logout_user, login_required
from btcbyme import db, bcrypt, limiter
from btcbyme.models import User, Message, MessageThread, Post
from btcbyme.users import forms
from btcbyme.utilities import utilities


users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
@limiter.limit('500/day; 100/hour;', override_defaults=True)
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index.home'))
    form = forms.RegistrationForm()
    if form.validate_on_submit():
        remote_ip_address = get_remote_address()
        if User.query.filter_by(remote_ip_address=remote_ip_address).count() == utilities.MAX_USER_COUNT_PER_IP:
            flash(f'Registration Unsuccessful. Maximum number of users met for this IP address {remote_ip_address}.',
                  'danger')
            return redirect(url_for('users.register'))
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        new_user = User(id=utilities.create_uuid(), username=form.username.data,
                        password=hashed_password, remote_ip_address=remote_ip_address)
        db.session.add(new_user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
@limiter.limit('500/day; 100/hour;', override_defaults=True)
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index.home'))
    form = forms.LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('index.home'))
        else:
            flash('Login Unsuccessful. Please check email and password.', 'danger')
    return render_template('login.html', title='Log In', form=form)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index.home'))


@users.route('/users/delete')
@login_required
def delete():
    user_message_threads = MessageThread.query.filter(
        (MessageThread.sender_id == current_user.get_id()) |
        (MessageThread.recipient_id == current_user.get_id())
    ).all()
    for thread in user_message_threads:
        thread_messages = Message.query.filter_by(thread_id=thread.id).all()
        for message in thread_messages:
            db.session.delete(message)
        db.session.delete(thread)
    user_posts = Post.query.filter_by(
        user_id=current_user.get_id()).order_by(Post.date_posted.desc())
    for post in user_posts:
        db.session.delete(post)
    user = User.query.get_or_404(current_user.get_id())
    db.session.delete(user)
    db.session.commit()
    flash(f'Your account has been successfully deleted!', 'success')
    return redirect(url_for('users.register'))


@users.route('/account')
@login_required
@limiter.limit('500/day; 100/hour;', override_defaults=True)
def account():
    user_view_data = utilities.get_user_view_data(User.query.filter_by(id=current_user.get_id()).first())
    user_posts = Post.query.filter_by(
        user_id=current_user.get_id()).order_by(Post.date_posted.desc()).all()
    user_posts_view_data = None if len(user_posts) == 0 else utilities.get_posts_view_data(user_posts)
    message_threads = MessageThread.query.filter(
        (MessageThread.sender_id == current_user.get_id()) |
        (MessageThread.recipient_id == current_user.get_id())
    ).order_by(MessageThread.date_updated.desc()).all()
    message_threads_view_data = utilities.get_message_thread_view_data(message_threads)
    return render_template(
        'account.html', title='Account', user_view_data=user_view_data, user_posts=user_posts_view_data,
        message_threads=message_threads_view_data)

btcbyme/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <div style="text-align: center;">
            <h1 class="page-header">Hi, {{ user_view_data.username }}!</h1>
            <h5><small class="text-muted">User since: {{ user_view_data.local_date_created }}</small></h5>
        </div>
        <div class="content-section" style="margin-top: 30px; padding-bottom: 30px;">
            <h3 class="page-header" style="margin-top: 15px;"><a href="{{ url_for('posts.index_posts') }}">My Posts</a></h3>
            {% if user_posts %}
                <div class="row row-cols-1 row-cols-lg-3">
                {% for post in user_posts %}
                    <div class="col">
                        <div class="card" style="margin-top: 15px;">
                            <div class="card-body">
                                <h5 class="card-title">{{ post.btc_price }} <small>{{ post.currency }}/BTC</small></h5>
                                <h6 class="card-subtitle mb-2 text-muted">{{ post.author_username }}</h6>
                                <p><b>Markup:</b><br>{{ post.markup_percentage }}</p>
                                <p><b>Transaction Range:</b><br>{{ post.min_tx }} - {{ post.max_tx }}</p>
                                <p>Location:<br>{{ post.city }}</p>
                                <div>
                                    <small class="text-muted">Date posted: {{ post.date_posted }}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
            {% else %}
                <p>No posts yet! Start a new post <a href="{{ url_for('posts.new_post') }}">here</a>!</p>
            {% endif %}
        </div>
        <div class="content-section" style="margin-top: 30px; padding-bottom: 30px;">
            <h3 class="page-header" style="margin-top: 15px;"><a href="{{ url_for('messages.index_messages') }}">My Message Threads</a></h3>
            {% if message_threads %}
                {% for thread in message_threads %}
                    <div class="card">
                        <div class="card-body">
                            <p>Subject post: <a href="{{ thread.post_url }}" class="card-link">{{ thread.post_url }}</a></p>
                            <p>Post owner: {{ thread.recipient_username }} <br> Interested user: {{ thread.sender_username }}</p>
                            <small class="text-muted">Most recent activity: {{ thread.date_updated_local }}</small>
                            <a href="{{ url_for('messages.message_thread', thread_id=thread.id) }}" class="stretched-link"></a>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p>No message threads yet! Search for posts to inquire about <a href="{{ url_for('posts.search_posts') }}">here</a>!</p>
            {% endif %}
        </div>
        <div class="content-section" style="margin-top: 30px; padding-bottom: 30px;">
            <h3 class="page-header" style="margin-top: 15px;">User Management</h3>
            <p style="margin-top: 30px;">
                <a class="btn btn-danger mb-2" href="{{ url_for('users.logout') }}">Log out</a>
                <a class="btn btn-danger mb-2" href="{{ url_for('users.delete') }}">Delete account</a>
            </p>
        </div>
    </div>
{% endblock %}

btcbyme/templates/how_it_works.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <h2 class="page-header">How it works for Buyers</h2>
        <div class="row">
            <div class="col-6">
                <div class="card" style="text-align: center; padding: 30px 10px 30px 10px;">
                    <div>
                        <img src="{{ url_for('static', filename='images/search.svg') }}" width="100px" height="100px" alt="">
                    </div>
                    <p style="margin-top: 15px;">1. <a href="{{ url_for('posts.search_posts') }}">Search</a> for posts that meet your interest.</p>
                </div>
            </div>
            <div class="col-6">
                <div class="card" style="text-align: center; padding: 30px 10px 30px 10px;">
                    <div>
                        <img src="{{ url_for('static', filename='images/message-square.svg') }}" width="100px" height="100px" alt="">
                    </div>
                    <p style="margin-top: 15px;">2. Send a message to the owner of the post.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <div class="card" style="text-align: center; padding: 30px 10px 30px 10px;">
                    <div>
                        <img src="{{ url_for('static', filename='images/map.svg') }}" width="100px" height="100px" alt="">
                    </div>
                    <p style="margin-top: 15px;">3. Discuss exchange details, including location, time, transaction amount, and transaction means (cash, wire, lightning, etc.).</p>
                </div>
            </div>
            <div class="col-6">
                <div class="card" style="text-align: center; padding: 30px 10px 30px 10px;">
                    <div>
                        <img src="{{ url_for('static', filename='images/repeat.svg') }}" width="100px" height="100px" alt="">
                    </div>
                    <p style="margin-top: 15px;">4. Meet IRL and complete the planned exchange.</p>
                </div>
            </div>
        </div>
        <h2 class="page-header">How it works for Sellers</h2>
       <div class="row">
            <div class="col-6">
                <div class="card" style="text-align: center; padding: 30px 10px 30px 10px;">
                    <div>
                        <img src="{{ url_for('static', filename='images/edit.svg') }}" width="100px" height="100px" alt="">
                    </div>
                    <p style="margin-top: 15px;">1. <a href="{{ url_for('posts.search_posts') }}">Create</a> a post in your local area.</p>
                </div>
            </div>
            <div class="col-6">
                <div class="card" style="text-align: center; padding: 30px 10px 30px 10px;">
                    <div>
                        <img src="{{ url_for('static', filename='images/watch.svg') }}" width="100px" height="100px" alt="">
                    </div>
                    <p style="margin-top: 15px;">2. Relax and wait for Buyers to find your post and express their interest.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <div class="card" style="text-align: center; padding: 30px 10px 30px 10px;">
                    <div>
                        <img src="{{ url_for('static', filename='images/map.svg') }}" width="100px" height="100px" alt="">
                    </div>
                    <p style="margin-top: 15px;">3. Discuss exchange details, including location, time, transaction amount, and transaction means (cash, wire, lightning, etc.).</p>
                </div>
            </div>
            <div class="col-6">
                <div class="card" style="text-align: center; padding: 30px 10px 30px 10px;">
                    <div>
                        <img src="{{ url_for('static', filename='images/repeat.svg') }}" width="100px" height="100px" alt="">
                    </div>
                    <p style="margin-top: 15px;">4. Meet IRL and complete the planned exchange.</p>
                </div>
            </div>
        </div>
        <h2 class="page-header">Some additional suggestions</h2>
        <p>Here are some additional suggestions for making the exchange process as seamless as possible.</p>
        <ul>
            <li>Meet in a public location, with plenty of people around.</li>
            <li>For larger transactions, ask to wait for at least one blockchain confirmation (more if time permits). Here is a decent <a href="https://www.buybitcoinworldwide.com/confirmations/">source</a> for some additional information concerning bitcoin blockchain confirmations.</li>
            <li>Try to discuss and confirm all of the details concerning the exchange prior to meeting in order to make the experience as efficient as possible.</li>
        </ul>
        <p>Feel free to send additional suggestions to <a href="mailto:support@btcbytme.com">support@btcbytme.com</a>, such that they could then find their way onto this list.</p>
    </div>
{% endblock %}

btcbyme/templates/index.html
{% extends "layout.html" %}
{% block content %}
    <div id="index-jumbotron" class="jumbotron jumbotron-fluid bg-cover text-white">
        <div class="container">
            <h1 class="display-5">Local, private, and physical, peer-to-peer Bitcoin exchange.</h1>
            <p class="lead">Find local Bitcoin users in your community to meet and exchange fiat currencies for Bitcoin, off the record.</p>
        </div>
    </div>
    <div class="container">
        <h3>Check out some of the most recent posts. Refine your search <a href="{{ url_for('posts.search_posts') }}">here</a>.</h3>
        {% if posts %}
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4">
            {% for post in posts %}
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ post.btc_price }} <small>{{ post.currency }}/BTC</small></h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ post.author_username }}</h6>
                            <p><b>Markup:</b><br>{{ post.markup_percentage }}</p>
                            <p><b>Transaction Range:</b><br>{{ post.min_tx }} - {{ post.max_tx }}</p>
                            <p>Location:<br>{{ post.city }}</p>
                            <div>
                                <a href="{{ url_for('messages.new_message_thread', post_id=post.id) }}" class="card-link">Send Message</a>
                            </div>
                            <div>
                                <small class="text-muted">Date posted: {{ post.date_posted }}</small>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        {% else %}
            <p>No posts available in your area. Please check back later.</p>
        {% endif %}
        <script src="{{ url_for('static', filename='js/index.js') }}"></script>
    </div>
{% endblock %}

btcbyme/templates/post.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <div class="col">
            <h2 class="page-header">Post ID: {{ post.id }}</h2>
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ post.btc_price }} <small>{{ post.currency }}/BTC</small></h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ post.author_username }}</h6>
                    <p><b>Markup:</b><br>{{ post.markup_percentage }}</p>
                    <p><b>Transaction Range:</b><br>{{ post.min_tx }} - {{ post.max_tx }}</p>
                    <p>Location:<br>{{ post.city }}</p>
                    <div>
                        <small class="text-muted">Date posted: {{ post.date_posted }}</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

btcbyme/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <h2 class="page-header">My Posts</h2>
        <div>
            <a class="btn btn-primary" href="{{ url_for('posts.new_post') }}" role="button" style="margin-top: 15px;">New Post</a>
        </div>
        {% if posts %}
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4">
            {% for post in posts %}
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ post.btc_price }} <small>{{ post.currency }}/BTC</small></h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ post.author_username }}</h6>
                            <p><b>Markup:</b><br>{{ post.markup_percentage }}</p>
                            <p><b>Transaction Range:</b><br>{{ post.min_tx }} - {{ post.max_tx }}</p>
                            <p>Location:<br>{{ post.city }}</p>
                            <div>
                                <!--TODO:Add modal confirmation-->
                                <button type="button" class="btn btn-outline-danger" onclick="location.href='{{ url_for('posts.delete_post', post_id=post.id) }}'">
                                    Delete
                                </button>
                            </div>
                            <div>
                                <small class="text-muted">Date posted: {{ post.date_posted }}</small>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        {% else %}
            <p style="margin-top: 30px;">Looks like you have no posts.</p>
        {% endif %}
    </div>
{% endblock %}